name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  repository_dispatch:
    types: [content-updated]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v7
          
      - name: Checkout content repository using git
        uses: actions/checkout@v7
        with:
          repository: "spark-hpi/docs"
          path: content/
          lfs: true
        
      - name: Install, build, and upload your site
        uses: withastro/action@v6
        env:
          CONTENT_PATH: content/res
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
